# Generated by Django 4.2.6 on 2023-10-15 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 15, 0, 43, 59, 80164, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
